# Generated by Django 5.2 on 2025-05-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('category', models.CharField(choices=[('web', 'Веб-разработка'), ('landing', 'Лендинг'), ('wp', 'Word-Press'), ('django', 'Django')], default='web', max_length=20)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(to='main.tag')),
            ],
        ),
    ]
